// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGyRD7xMX9wUKkaZnzFveId8jmdpssxs',
    appId: '1:898421442078:web:50aa1da7207389ea9d500f',
    messagingSenderId: '898421442078',
    projectId: 'newpr-a448c',
    authDomain: 'newpr-a448c.firebaseapp.com',
    storageBucket: 'newpr-a448c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEyaBW175vj_hfWCKzt7GwStq6kiyXN8',
    appId: '1:898421442078:android:b4b0d3b6a072f0c49d500f',
    messagingSenderId: '898421442078',
    projectId: 'newpr-a448c',
    storageBucket: 'newpr-a448c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6P8N5GibCXRO3XvL3nh5WZ6VQXQK3WVY',
    appId: '1:898421442078:ios:f59c2f1a4e242b5b9d500f',
    messagingSenderId: '898421442078',
    projectId: 'newpr-a448c',
    storageBucket: 'newpr-a448c.firebasestorage.app',
    androidClientId: '898421442078-4ggr91jclpied8luse7ibhncbrrmhnib.apps.googleusercontent.com',
    iosClientId: '898421442078-0l6n6ppohdva274cf70dr3m8f5eg4l5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapakBantulProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6P8N5GibCXRO3XvL3nh5WZ6VQXQK3WVY',
    appId: '1:898421442078:ios:f59c2f1a4e242b5b9d500f',
    messagingSenderId: '898421442078',
    projectId: 'newpr-a448c',
    storageBucket: 'newpr-a448c.firebasestorage.app',
    androidClientId: '898421442078-4ggr91jclpied8luse7ibhncbrrmhnib.apps.googleusercontent.com',
    iosClientId: '898421442078-0l6n6ppohdva274cf70dr3m8f5eg4l5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapakBantulProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtGyRD7xMX9wUKkaZnzFveId8jmdpssxs',
    appId: '1:898421442078:web:434aa3481002e3759d500f',
    messagingSenderId: '898421442078',
    projectId: 'newpr-a448c',
    authDomain: 'newpr-a448c.firebaseapp.com',
    storageBucket: 'newpr-a448c.firebasestorage.app',
  );
}
